---
services:
  besu_node:
    restart: unless-stopped
    container_name: besu
    environment:
      - "JAVA_OPTS=-Xmx5g"
    image: hyperledger/besu:latest
    command:
      [
       "--network=mainnet",
       "--rpc-http-enabled=true",
       "--rpc-http-host =0.0.0.0",
       "--data-path=/var/lib/besu",
       "--rpc-ws-enabled",
       "--metrics-enabled",
       "--sync-mode=SNAP",
       "--data-storage-format=BONSAI",
       "--Xbonsai-limit-trie-logs-enabled=true",
       "--Xplugin-rocksdb-high-spec-enabled",
       "--engine-jwt-secret=/secrets/jwtsecret.hex",
       "--engine-rpc-enabled=true",
       "--engine-host-allowlist=*",
       "--host-allowlist=*",
       "--max-peers=25"
       ]
    volumes:
      - ${DATA\PATH}/besu:/var/lib/besu
      - /secrets/jwtsecret:/secrets/jwtsecret
    ports:
      # Map the p2p port(30303), RPC HTTP port(8545), and engine port (8551)
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"

  teku_node:
    restart: unless-stopped
    container_name: teku
    environment:
      - "JAVA_OPTS=-Xmx6g"
    image: consensys/teku:latest
    command:
      [
       "--network=mainnet", 
       "--data-base-path=/var/lib/teku",
       "--data-storage-mode=minimal",
       "--initial-state="https://beaconstate.info" ,
       "--validators-proposer-default-fee-recipient=",
       "--ee-endpoint=http://besu_node:8551",
       "--ee-jwt-secret-file=/secrets/jwtsecret.hex",
       "--p2p-port=9000",
       "--rest-api-enabled=true",
       "--rest-api-port=5052",
       "--rest-api-docs-enabled=true",
       "--rest-api-host-allowlist=*",
       "--p2p-peer-upper-bound=100",
       "--p2p-peer-lower-bound=60",
       "--metrics-enabled=true",
       "--metrics-port=8008",
       "--builder-endpoint=http://mev_boost:18550",
      ]
    depends_on:
      - besu_node
    volumes:
      - ${DATA\PATH}/teku:/var/lib/teku

    ports:
      # Map the p2p port(9000) and REST API port(5051)
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "5051:5051"
      - "8008:8008"
      - "5052:5052"

  mev_boost:
    restart: unless-stopped
    container_name: mev_boost
    image: flashbots/mev-boost:latest
    command: 
      [
       "-mainnet",
       "-relay-check",
       "-min-bid=0.03",
       "-addr=0.0.0.0:18550",
       "-relay=https://0x8c4ed5e24fe5c6ae21018437bde147693f68cda427cd1122cf20819c30eda7ed74f72dece09bb313f2a1855595ab677d@global.titanrelay.xyz"
       "-relay=https://0x8c4ed5e24fe5c6ae21018437bde147693f68cda427cd1122cf20819c30eda7ed74f72dece09bb313f2a1855595ab677d@regional.titanrelay.xyz",
       "-relay=https://0xa7ab7a996c8584251c8f925da3170bdfd6ebc75d50f5ddc4050a6fdc77f2a3b5fce2cc750d0865e05d7228af97d69561@agnostic-relay.net",
       "-relay=https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money",
       "-relay=https://0xa15b52576bcbf1072f4a011c0f99f9fb6c66f3e1ff321f11f461d15e31b1cb359caa092c71bbded0bae5b5ea401aab7e@aestus.live",
       "-relay=https://0x98650451ba02064f7b000f5768cf0cf4d4e492317d82871bdc87ef841a0743f69f0f1eea11168503240ac35d101c9135@mainnet-relay.securerpc.com/",
       "-relay=https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net",
       "-relay=https://0x8b5d2e73e2a3a55c6c87b8b6eb92e0149a125c852751db1422fa951e42a09b82c142c3ea98d0d9930b056a3bc9896b8f@bloxroute.max-profit.blxrbdn.com",
       "-relay=https://0xb0b07cd0abef743db4260b0ed50619cf6ad4d82064cb4fbec9d3ec530f7c5e6793d9f286c4e082c0244ffb9f2658fe88@bloxroute.regulated.blxrbdn.com",
      ]
    ports:
      - "18550:18550"

  ssv_node:
    restart: unless-stopped
    container_name: ssv
    environment:
      - "CONFIG_PATH=/config.yaml"
    image: bloxstaking/ssv-node:latest
    command:
      make BUILD_PATH="/go/bin/ssvnode" start-node
    depends_on:
      - besu_node
      - teku_node
    volumes:
      - ./ssv/config.yaml:/config.yaml
      - ${DATA\PATH}/ssv/data:/data 
      - ./ssv/password:/password 
      - ./ssv/encrypted_private_key.json:/encrypted_private_key.json 
    ports:
      - 13001:13001
      - 12001:12001/udp
      - 15000:15000
  

